config/routes.rb
Rails.application.routes.draw do
  root to: 'addresses#new'
  resources :addresses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  validates :house_number, presence: true
  validates :street_name, presence: true
  validates :city, presence: true
  validates :state, presence: true, length: { is: 2 }
  validates :zip_5, presence: true, numericality: true, length: { is: 5 }

  def to_s
    street = [
      house_number, street_predirection, street_name, street_type,
      street_postdirection, unit_type, unit_number
    ].reject(&:blank?).join(' ')
    state_zip = [ state, zip_5 ].join(' ')

    [ street, city, state_zip ].join(', ')
  end
end

app/models/address_verification.rb
class AddressVerification
  class VerificationError < StandardError; end

  include ActiveModel::Model

  attr_accessor :street_address, :city, :state, :zip_code
  attr_reader :verification

  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true,
    numericality: true,
    length: { is: 5 }

  define_model_callbacks :save
  before_save :validate_deliverability

  def save
    return false unless valid?
    run_callbacks :save
    errors.empty?
  end

  def deliverable?
    verification['deliverability'] == 'deliverable'
  end

  def to_address_params
    {
      house_number: verification['components']['primary_number'],
      street_name: verification['components']['street_name'],
      street_type: verification['components']['street_suffix'],
      street_predirection: verification['components']['street_predirection'],
      street_postdirection: verification['components']['street_postdirection'],
      unit_number: verification['components']['secondary_designator'],
      unit_type: verification['components']['secondary_number'],
      city: verification['components']['city'],
      state: verification['components']['state'],
      county: verification['components']['county'],
      zip_5: verification['components']['zip_code'],
      zip_4: verification['components']['zip_code_plus_4']
    }
  end


  private

  def lob_client
    @lob_client ||= Lob::Client.new(api_key: ENV['LOB_SECRET_API_KEY'])
  end

  def verify
    @verification = lob_client.us_verifications.verify(
      primary_line: street_address,
      city: city,
      state: state,
      zip_code: zip_code
    )
  end

  def validate_deliverability
    verify
    errors.add(:street_address, :invalid, message: 'is not a deliverable address') unless deliverable?
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
    @address_verification = AddressVerification.new
    render 'new'
  end

  def show
    @address = Address.find(params[:id])
  end

  def new
    @address_verification = AddressVerification.new
  end

  def create
    @address_verification = AddressVerification.new(address_verification_params)

    if @address_verification.save
      @address = Address.create(@address_verification.to_address_params)
      redirect_to @address, notice: 'Address successfully validated!'
    else
      render 'new'
    end
  end

  private

  def address_verification_params
    params.require(:address_verification)
      .permit(:street_address, :city, :state, :zip_code)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/addresses_helper.rb
module AddressesHelper
  def state_abbreviations
    %w(
      AL AK AZ AR CA CO CT DE DC FL GA HI ID IL IN IA KS KY LA ME MD MA MI
      MN MS MO MT NE NV NH NJ NM NY NC ND OH OK OR PA PR RI SC SD TN TX UT
      VA VT VI WA WI WY
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/new.html.erb
<%= form_for @address_verification, url: addresses_path do |f| %>
  <div class="form-title">
    <h2>Address Validator<h2>
  </div>

  <div class="form-body">
    <% if @address_verification.errors.any? %>
      <div class="form-errors">
        <h3 class="error-heading">
          <%= pluralize(@address_verification.errors.count, 'error') %>
          prevented this form from being saved:
        </h3>
        <ul>
          <% @address_verification.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-control">
      <%= f.label :street_address, 'Street address <em>*</em>'.html_safe %>
      <%= f.text_field :street_address %>
    </div>

    <div class="form-control">
      <span id="address-city">
        <%= f.label :city, 'City <em>*</em>'.html_safe %>
        <%= f.text_field :city %>
      </span>

      <span id="address-state">
        <%= f.label :state, 'State <em>*</em>'.html_safe %>
        <%= f.select :state, state_abbreviations %>
      </span>

      <span id="address-zip">
        <%= f.label :zip_code, 'Zip <em>*</em>'.html_safe %>
        <%= f.text_field :zip_code, size: 5 %>
      </span>
    </div>

    <div class = "buttons">
      <%= f.submit 'Validate Address' %>
    </div>
  </div>
<% end %>

app/views/addresses/show.html.erb
<div class="container">
  <h1>Validated Address</h1>

  <%= @address.to_s %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AddressValidator</title>
    <%= csrf_meta_tags %>

    <link rel="icon" href="https://www.vote.org/wp-content/themes/votedotorg/dist/images/favicons/favicon.ico">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <a href="https://github.com/kwiest/address-validator-master">
      <img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png" alt="Fork me on GitHub">
    </a>
    <header>
      <div class="vdo-logo">
        <%= image_tag 'vdo-logo-32x32.png' %>
        <h1>Vote.org</h1>
      </div>
    </header>

    <%= yield %>
  </body>
</html>